package rogue.game.combat.skills;

import java.util.HashMap;
import java.util.Map;

import rogue.game.combat.skills.individualskills.AllyHeal;
import rogue.game.combat.skills.individualskills.AreaFire;
import rogue.game.combat.skills.individualskills.Barrage;
import rogue.game.combat.skills.individualskills.Behead;
import rogue.game.combat.skills.individualskills.BindingSpell;
import rogue.game.combat.skills.individualskills.C4;
import rogue.game.combat.skills.individualskills.CalmBeast;
import rogue.game.combat.skills.individualskills.Cerebro;
import rogue.game.combat.skills.individualskills.Condemn;
import rogue.game.combat.skills.individualskills.CrowScout;
import rogue.game.combat.skills.individualskills.DemonicForm;
import rogue.game.combat.skills.individualskills.DuelToTheDeath;
import rogue.game.combat.skills.individualskills.Enhance;
import rogue.game.combat.skills.individualskills.EnhancementField;
import rogue.game.combat.skills.individualskills.Explosion;
import rogue.game.combat.skills.individualskills.FastShots;
import rogue.game.combat.skills.individualskills.FireArmor;
import rogue.game.combat.skills.individualskills.FireRing;
import rogue.game.combat.skills.individualskills.FireStream;
import rogue.game.combat.skills.individualskills.Fireball;
import rogue.game.combat.skills.individualskills.FistFury;
import rogue.game.combat.skills.individualskills.FlameWhip;
import rogue.game.combat.skills.individualskills.Flying;
import rogue.game.combat.skills.individualskills.ForceChoke;
import rogue.game.combat.skills.individualskills.ForceLeap;
import rogue.game.combat.skills.individualskills.ForcePush;
import rogue.game.combat.skills.individualskills.FrostWalk;
import rogue.game.combat.skills.individualskills.GhostDeath;
import rogue.game.combat.skills.individualskills.Grapple;
import rogue.game.combat.skills.individualskills.GrowGrass;
import rogue.game.combat.skills.individualskills.HatefulSwing;
import rogue.game.combat.skills.individualskills.Heal;
import rogue.game.combat.skills.individualskills.Hexproof;
import rogue.game.combat.skills.individualskills.HitOrMiss;
import rogue.game.combat.skills.individualskills.Lifelink;
import rogue.game.combat.skills.individualskills.LordVile;
import rogue.game.combat.skills.individualskills.MassBleeding;
import rogue.game.combat.skills.individualskills.Maul;
import rogue.game.combat.skills.individualskills.MurderFest;
import rogue.game.combat.skills.individualskills.Outlast;
import rogue.game.combat.skills.individualskills.Phoenixportation;
import rogue.game.combat.skills.individualskills.PlantTree;
import rogue.game.combat.skills.individualskills.PreciseShot;
import rogue.game.combat.skills.individualskills.Psyshock;
import rogue.game.combat.skills.individualskills.Rage;
import rogue.game.combat.skills.individualskills.Resistant;
import rogue.game.combat.skills.individualskills.RighteousSwing;
import rogue.game.combat.skills.individualskills.RockThrow;
import rogue.game.combat.skills.individualskills.SacrificialCurse;
import rogue.game.combat.skills.individualskills.SendIdefix;
import rogue.game.combat.skills.individualskills.ShadowSpears;
import rogue.game.combat.skills.individualskills.ShadowWalk;
import rogue.game.combat.skills.individualskills.ShadowWave;
import rogue.game.combat.skills.individualskills.Shield;
import rogue.game.combat.skills.individualskills.ShowArea;
import rogue.game.combat.skills.individualskills.SmokeScreen;
import rogue.game.combat.skills.individualskills.StunningSpell;
import rogue.game.combat.skills.individualskills.SummonGoblin;
import rogue.game.combat.skills.individualskills.SummonHellspawn;
import rogue.game.combat.skills.individualskills.SummonSpider;
import rogue.game.combat.skills.individualskills.SummonZombie;
import rogue.game.combat.skills.individualskills.Tarning;
import rogue.game.combat.skills.individualskills.Telekinesis;
import rogue.game.combat.skills.individualskills.Teleport;
import rogue.game.combat.skills.individualskills.ThrowingWeapon;
import rogue.game.combat.skills.individualskills.Torture;
import rogue.game.combat.skills.individualskills.Trap;
import rogue.game.combat.skills.individualskills.TrueVision;
import rogue.game.combat.skills.individualskills.Underdog;
import rogue.game.combat.skills.individualskills.Unstoppable;
import rogue.game.combat.skills.individualskills.WeaponThrow;
import rogue.game.combat.skills.individualskills.WideSwing;
import rogue.game.combat.skills.individualskills.WindWall;
import rogue.game.combat.skills.individualskills.WoodWalk;

public class SkillLibrary {
	
	public static int NONE = 0;
	public static int SHOW_AREA = 14;
	public static int ZOMBIE_MINIONS = 1;
	public static int HEART_SHOT = 2;
	public static int STURDY = 3;
	public static int FIEND_FYRE = 4;
	public static int MURDER_FEST = 5;
	public static int PSYSHOCK = 6;
	public static int STUN = 7;
	public static int HATEFUL_SWING = 8;
	public static int WEAPON_THROW = 9;
	public static int FORCE_CHOKE = 10;
	public static int MERCILESS_MASSACRE = 11;
	public static int RIGHTEOUS_SWING = 12;
	public static int FORCE_PUSH = 13;
	public static int SHOCKWAVE_JUMP = 15;
	public static int UNSTOPPABLE = 16;
	public static int CONDEMN = 17;
	public static int LAST_RESERVE = 18;
	public static int FLAMETHROWER = 19;
	public static int ROCKET = 20;
	public static int JETPACK_BOOST = 21;
	public static int BACTA_PAD = 22;
	public static int ALL_TERRAIN = 23;
	public static int ALLY_HEAL = 24;
	public static int ALLY_SHIELD = 25;
	public static int ARAGOG = 26;
	public static int AREAFIRE = 27;
	public static int ARROW_BARRAGE = 28;
	public static int ARROW_SHOTS = 29;
	public static int AVADA_KEDAVRA = 30;
	public static int BATARANG = 31;
	public static int BEHEAD = 32;
	public static int BE_TOSSED = 33;
	public static int BLIND = 34;
	public static int BLUDGER = 35;
	public static int BONDING = 36;
	public static int CAMOUFLAGE = 37;
	public static int CEREBRO = 38;
	public static int COUNT_KILLS = 39;
	public static int CLAW_TO_LIFE = 40;
	public static int CROW_SCOUT = 41;
	public static int CRUCIO = 42;
	public static int DAGGER_THROW = 43;
	public static int DEMONIC_FORM = 44;
	public static int DISARM = 45;
	public static int DISGUISE = 46;
	public static int EDUCATIONAL_DECREE_NO_4 = 47;
	public static int EMPTY_REVOLVER = 48;
	public static int ENERGY_BIND = 49;
	public static int ENHANCEMENT_RUNE = 50;
	public static int EQUIPMENT_UPGRADE = 51;
	public static int EVASIVE = 52;
	public static int EVERYTHING_BURNS = 53;
	public static int FELL_IN_THE_POT = 54;
	public static int FERRETFORMATION = 55;
	public static int FIRE_ARMOR = 56;
	public static int FIREBALL = 57;
	public static int FIRE_RING = 58;
	public static int FLAME_WHIP = 59;
	public static int FLUFFY = 60;
	public static int GIANT_HAWK = 61;
	public static int GRAPPLING_HOOK = 62;
	public static int GRAWP = 63;
	public static int GUARD_AREA = 64;
	public static int HIPPOGRYFF = 65;
	public static int HOLLOW_MAN = 66;
	public static int HORCRUX = 67;
	public static int ILLUSION = 68;
	public static int IMPERIO = 69;
	public static int I_SHALL_NOT_TELL_LIES = 70;
	public static int LIGHTNING_STRIKE = 71;
	public static int LORD_VILLE = 72;
	public static int FIST_BARRAGE = 73;
	public static int NORMAL_FORM = 74;
	public static int OCCULT_KNOWLEDGE = 75;
	public static int PETRIFY = 76;
	public static int PHOENIX_TELEPORTATION = 77;
	public static int PLANT = 78;
	public static int RABBIT_SLED = 79;
	public static int ROCK_THROW = 80;
	public static int ROPES = 81;
	public static int RUNE_TRAP = 82;
	public static int SEND_IDEFIX = 84;
	public static int SHADOW_ARMOR = 85;
	public static int SHADOW_SPEARS = 86;
	public static int SHADOW_WALK = 87;
	public static int SHADOW_WALL = 88;
	public static int SHADOW_WAVE = 89;
	public static int SKULLDUGGERY = 90;
	public static int SMOKE_SCREEN = 91;
	public static int STUPOR = 92;
	public static int TALL_GRASS = 93;
	public static int TARNING = 94;
	public static int TAUNT = 95;
	public static int TELEPORT = 96;
	public static int TEND_THE_GARDEN = 97;
	public static int THROW_GRANADE = 98;
	public static int TOSSIN = 99;
	public static int TRACKING = 100;
	public static int TRUE_VISION = 101;
	public static int VOODOO_SHIT = 102;
	public static int WEAPON_SWING = 103;
	public static int WIND_WALL = 104;
	public static int WOOD_WALK = 105;
	public static int DUEL_TO_THE_DEATH=106;
	
	public static int FROSTWALK = 107;
	public static int MAUL = 108;
	public static int C4 = 109;
	public static int CALM_BEAST = 110;
	public static int GHOST_DEATH=111;
	public static int UNDERDOG = 112;
	public static int HIT_OR_MISS = 113;
	public static int SUMMON_GOBLIN = 114;
	public static int OUTLAST = 115;
	public static int LIFELINK = 116;
	public static int SACRIFICIAL_CURSE = 117;
	public static int HEXPROOF = 118;
	
	public static Map<Integer,Class> skills = new HashMap<>();
	
	public static void init() {
		skills.put(AREAFIRE,AreaFire.class);
		skills.put(ARROW_BARRAGE,Barrage.class);
		skills.put(ROPES,BindingSpell.class);
		skills.put(CEREBRO,Cerebro.class);
		skills.put(CONDEMN,Condemn.class);
		skills.put(CROW_SCOUT, CrowScout.class);
		skills.put(DEMONIC_FORM, DemonicForm.class);
		skills.put(DUEL_TO_THE_DEATH,DuelToTheDeath.class);
		skills.put(EQUIPMENT_UPGRADE, Enhance.class);
		skills.put(ROCKET, Explosion.class);
		skills.put(EMPTY_REVOLVER,FastShots.class);
		skills.put(FIRE_ARMOR,FireArmor.class);
		skills.put(FIREBALL,Fireball.class);
		skills.put(FIRE_RING,FireRing.class);
		skills.put(FLAMETHROWER,FireStream.class);
		skills.put(FIST_BARRAGE,FistFury.class);
		skills.put(FLAME_WHIP,FlameWhip.class);
		skills.put(ALL_TERRAIN,Flying.class);
		skills.put(FORCE_CHOKE,ForceChoke.class);
		skills.put(SHOCKWAVE_JUMP,ForceLeap.class);
		skills.put(FORCE_PUSH,ForcePush.class);
		skills.put(GRAPPLING_HOOK,Grapple.class);
		skills.put(TALL_GRASS,GrowGrass.class);
		skills.put(HATEFUL_SWING,HatefulSwing.class);
		skills.put(TEND_THE_GARDEN,Heal.class);
		skills.put(LORD_VILLE,LordVile.class);
		skills.put(I_SHALL_NOT_TELL_LIES,MassBleeding.class);
		skills.put(MURDER_FEST,MurderFest.class);
		skills.put(PHOENIX_TELEPORTATION,Phoenixportation.class);
		skills.put(PLANT,PlantTree.class);
		skills.put(HEART_SHOT,PreciseShot.class);
		skills.put(PSYSHOCK,Psyshock.class);
		skills.put(MERCILESS_MASSACRE,Rage.class);
		skills.put(FELL_IN_THE_POT,Resistant.class);
		skills.put(RIGHTEOUS_SWING,RighteousSwing.class);
		skills.put(ROCK_THROW,RockThrow.class);
		skills.put(SEND_IDEFIX,SendIdefix.class);
		skills.put(SHADOW_SPEARS,ShadowSpears.class);
		skills.put(SHADOW_WALK,ShadowWalk.class);
		skills.put(SHADOW_WAVE,ShadowWave.class);
		skills.put(ALLY_SHIELD,Shield.class);
		skills.put(SHOW_AREA,ShowArea.class);
		skills.put(SMOKE_SCREEN,SmokeScreen.class);
		skills.put(STUPOR,StunningSpell.class);
		skills.put(ZOMBIE_MINIONS,SummonZombie.class);
		skills.put(ARAGOG,SummonSpider.class);
		skills.put(FLUFFY,SummonHellspawn.class);
		skills.put(TARNING,Tarning.class);
		skills.put(BLUDGER,Telekinesis.class);
		skills.put(TELEPORT,Teleport.class);
		skills.put(BATARANG,ThrowingWeapon.class);
		skills.put(CRUCIO,Torture.class);
		skills.put(RUNE_TRAP,Trap.class);
		skills.put(TRUE_VISION,TrueVision.class);
		skills.put(UNSTOPPABLE,Unstoppable.class);
		skills.put(WEAPON_THROW,WeaponThrow.class);
		skills.put(WEAPON_SWING,WideSwing.class);
		skills.put(WIND_WALL,WindWall.class);
		skills.put(WOOD_WALK,WoodWalk.class);
		skills.put(ALLY_HEAL,AllyHeal.class);
		
		skills.put(C4,C4.class);
		skills.put(ENHANCEMENT_RUNE,EnhancementField.class);
		skills.put(FROSTWALK,FrostWalk.class);
		skills.put(MAUL, Maul.class);
		skills.put(CALM_BEAST,CalmBeast.class);
		skills.put(GHOST_DEATH,GhostDeath.class);
		skills.put(UNDERDOG,Underdog.class);
		skills.put(HIT_OR_MISS,HitOrMiss.class);
		skills.put(SUMMON_GOBLIN,SummonGoblin.class);
		skills.put(OUTLAST,Outlast.class);
		skills.put(LIFELINK,Lifelink.class);
		skills.put(SACRIFICIAL_CURSE,SacrificialCurse.class);
		skills.put(HEXPROOF,Hexproof.class);
		skills.put(BEHEAD,Behead.class);
	}
	public static Skill get(int id) {
		try {
			return Skill.class.cast(skills.get(id).newInstance());
		} catch (InstantiationException e) {
			e.printStackTrace();
		} catch (IllegalAccessException e) {
			e.printStackTrace();
		}
		return null;
	}
//	public static Skill getSkill(int id) {
//		Skill copy = new Skill();
//		copy.setAccuracy(skills.get(id).getAccuracy());
//		copy.setActionCost(skills.get(id).getActionCost());
//		copy.setBlocked(skills.get(id).isBlocked());
//		copy.setDamageType(skills.get(id).getDamageType());
//		copy.setDescription(skills.get(id).getDescription());
//		copy.setDistance(skills.get(id).getDistance());
//		copy.setEffects(skills.get(id).getEffects());
//		copy.setEvent(skills.get(id).getEvent());
//		copy.setId(skills.get(id).getId());
//		copy.setLifeCost(skills.get(id).getLifeCost());
//		copy.setManaCost(skills.get(id).getManaCost());
//		copy.setMultipliers(skills.get(id).getMultipliers());
//		copy.setName(skills.get(id).getName());
//		copy.setPower(skills.get(id).getPower());
//		copy.setRadius(skills.get(id).getRadius());
//		copy.setSummonedId(skills.get(id).getSummonedId());
//		copy.setTarget(skills.get(id).getTarget());
//		copy.setType(skills.get(id).getType());
//		return copy;
//	}
}
