package rogue.framework.resources;

import rogue.game.combat.skills.SkillLibrary;
import rogue.game.npc.NPCLibrary;
import rogue.game.pvp.CharacterLibrary;
import rogue.game.world.objects.ObjectLibrary;

public class Loader {
	public static void load() {
		
		SkillLibrary.init();
		CharacterLibrary.init();
		NPCLibrary.init();
		ObjectLibrary.init();
		
		Resources.TEXTURES.add(Resources.VOID,new Sprite("res/textures/void.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.TEXTURES.add(Resources.BRICK,new Sprite("res/textures/brick.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.TEXTURES.add(Resources.WALL,new Sprite("res/textures/wall.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.TEXTURES.add(Resources.ENDWALL,new Sprite("res/textures/wall.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.TEXTURES.add(Resources.MEADOW,new Sprite("res/textures/meadow.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.TEXTURES.add(Resources.TREE,new Sprite("res/textures/tree.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.TEXTURES.add(Resources.TALLGRASS,new Sprite("res/textures/tallgrass.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.TEXTURES.add(Resources.SMOKE_SCREEN,new Sprite("res/textures/smokescreen.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.TEXTURES.add(Resources.WATER,new Sprite("res/textures/water.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		
		Resources.CHARACTERS.add(Resources.KNIGHT,new Sprite("res/characters/knight.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.SKELETON,new Sprite("res/characters/skeleton.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.SPONGEBOB,new Sprite("res/characters/spongebob.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.DARTH_SION,new Sprite("res/characters/sion.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.DARTH_VADER,new Sprite("res/characters/vader.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.LUKE,new Sprite("res/characters/luke.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.BOBA,new Sprite("res/characters/boba.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.BALROG,new Sprite("res/characters/balrog.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.BATMAN,new Sprite("res/characters/batman.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.BAUMBART,new Sprite("res/characters/baumbart.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.CHINA,new Sprite("res/characters/china.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.DOBBY,new Sprite("res/characters/dobby.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.DUMBLEDORE,new Sprite("res/characters/dumbledore.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.GIMLI,new Sprite("res/characters/gimli.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.GRAESSLICH,new Sprite("res/characters/graesslich.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.HAGRID,new Sprite("res/characters/hagrid.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.HELLBOY,new Sprite("res/characters/hellboy.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.LEGOLAS,new Sprite("res/characters/legolas.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.MOODY,new Sprite("res/characters/moody.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.OBELIX,new Sprite("res/characters/obelix.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.PROFESSOR,new Sprite("res/characters/professor.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.R2D2,new Sprite("res/characters/r2d2.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.RADAGAST,new Sprite("res/characters/radagast.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.SAMWISE,new Sprite("res/characters/samwise.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.SERPINE,new Sprite("res/characters/serpine.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.SKULDUGGERY,new Sprite("res/characters/skulduggery.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.SOLOMON,new Sprite("res/characters/solomon.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.TALZIN,new Sprite("res/characters/talzin.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.UMBRIDGE,new Sprite("res/characters/umbridge.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.V,new Sprite("res/characters/v.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.VOLDEMORT,new Sprite("res/characters/voldemort.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.WHITESCYTHE,new Sprite("res/characters/whitescythe.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.LUKE_ASTRAL,new Sprite("res/characters/luke.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		Resources.CHARACTERS.add(Resources.ZOMBIE,new Sprite("res/npcs/zombie.png",Property.TILE_SIZE,Property.TILE_SIZE).getPixels());
		
		
		Resources.PORTRAITSx64.add(Resources.DUMMY,new Sprite("res/skills/lockedskill.png",64,64).getPixels());
		Resources.PORTRAITSx64.add(Resources.SKELETONMALE,new Sprite("res/portraits/skeletonPortraitMale.png",64,64).getPixels());
		Resources.PORTRAITSx64.add(Resources.P_BOBA,new Sprite("res/portraits/p_boba.png",64,64).getPixels());
		Resources.PORTRAITSx64.add(Resources.P_VADER,new Sprite("res/portraits/p_vader.png",64,64).getPixels());
		Resources.PORTRAITSx64.add(Resources.P_D_SION,new Sprite("res/portraits/p_d_sion.png",64,64).getPixels());
		Resources.PORTRAITSx64.add(Resources.P_LUKE,new Sprite("res/portraits/p_luke.png",64,64).getPixels());
			
		Resources.PORTRAITSx32.add(Resources.MOVEMENT_ACTION,new Sprite("res/icons/movement.png",32,32).getPixels());
		Resources.PORTRAITSx32.add(Resources.ATTACK_ACTION,new Sprite("res/icons/attack.png",32,32).getPixels());
		Resources.PORTRAITSx32.add(Resources.CONFIRM_ACTION,new Sprite("res/icons/confirm.png",32,32).getPixels());
		Resources.PORTRAITSx32.add(Resources.END_TURN_ACTION,new Sprite("res/icons/endTurn.png",32,32).getPixels());
		Resources.PORTRAITSx32.add(Resources.CANCEL_ACTION,new Sprite("res/icons/cancel.png",32,32).getPixels());
		Resources.PORTRAITSx32.add(Resources.UP,new Sprite("res/icons/up.png",32,32).getPixels());
		Resources.PORTRAITSx32.add(Resources.DOWN,new Sprite("res/icons/down.png",32,32).getPixels());
		
		Resources.PORTRAITSx32.add(SkillLibrary.NONE,new Sprite("res/skills/lockedskill.png",32,32).getPixels());
		Resources.PORTRAITSx32.add(SkillLibrary.HATEFUL_SWING,new Sprite("res/skills/hatefulswing.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.WEAPON_THROW,new Sprite("res/skills/weaponthrow.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.FORCE_CHOKE,new Sprite("res/skills/forcechoke.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.MERCILESS_MASSACRE,new Sprite("res/skills/mercilessmassacre.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.RIGHTEOUS_SWING,new Sprite("res/skills/righteousswing.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.FORCE_PUSH,new Sprite("res/skills/forcepush.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.FORCE_VISION,new Sprite("res/skills/forceprojection.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.SHOCKWAVE_JUMP,new Sprite("res/skills/shockwavejump.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.UNSTOPPABLE,new Sprite("res/skills/unstoppable.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.CONDEMN,new Sprite("res/skills/condemn.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.LAST_RESERVE,new Sprite("res/skills/lastreserver.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.FLAMETHROWER,new Sprite("res/skills/flamethrower.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.ROCKET,new Sprite("res/skills/rocket.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.JETPACK_BOOST,new Sprite("res/skills/jetpackboost.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.BACTA_PAD,new Sprite("res/skills/bactapad.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.ALL_TERRAIN,new Sprite("res/skills/allterrain.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.ALLY_HEAL,new Sprite("res/skills/allyheal.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.ALLY_SHIELD,new Sprite("res/skills/allyshield.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.ARAGOG,new Sprite("res/skills/aragog.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.AREAFIRE,new Sprite("res/skills/areafire.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.ARROW_BARRAGE,new Sprite("res/skills/arrowbarrage.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.ARROW_SHOTS,new Sprite("res/skills/arrowshots.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.AVADA_KEDAVRA,new Sprite("res/skills/avadakedavra.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.BATARANG,new Sprite("res/skills/batarang.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.BEHEAD,new Sprite("res/skills/behead.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.BE_TOSSED,new Sprite("res/skills/betossed.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.BLIND,new Sprite("res/skills/blind.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.BLUDGER,new Sprite("res/skills/bludger.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.BONDING,new Sprite("res/skills/bonding.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.CAMOUFLAGE,new Sprite("res/skills/camouflage.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.CEREBRO,new Sprite("res/skills/cerebro.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.COUNT_KILLS,new Sprite("res/skills/countkills.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.CLAW_TO_LIFE,new Sprite("res/skills/crawltolife.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.CROW_SCOUT,new Sprite("res/skills/crowscout.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.CRUCIO,new Sprite("res/skills/crucio.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.DAGGER_THROW,new Sprite("res/skills/daggerthrow.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.DEMONIC_FORM,new Sprite("res/skills/demonicform.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.DISARM,new Sprite("res/skills/deweaponize.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.DISGUISE,new Sprite("res/skills/disguise.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.EDUCATIONAL_DECREE_NO_4,new Sprite("res/skills/educationaldecreeno72.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.EMPTY_REVOLVER,new Sprite("res/skills/emptyrevolver.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.ENERGY_BIND,new Sprite("res/skills/energybind.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.ENHANCEMENT_RUNE,new Sprite("res/skills/enhancementrune.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.EQUIPMENT_UPGRADE,new Sprite("res/skills/equipmentupgrade.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.EVASIVE,new Sprite("res/skills/evasive.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.EVERYTHING_BURNS,new Sprite("res/skills/everythingburns.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.FELL_IN_THE_POT,new Sprite("res/skills/fellinthepot.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.FERRETFORMATION,new Sprite("res/skills/ferretformation.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.FIRE_ARMOR,new Sprite("res/skills/firearmor.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.FIREBALL,new Sprite("res/skills/fireball.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.FIRE_RING,new Sprite("res/skills/firering.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.FLAME_WHIP,new Sprite("res/skills/flamewhip.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.FLUFFY,new Sprite("res/skills/fluffy.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.GIANT_HAWK,new Sprite("res/skills/gianthawk.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.GRAPPLING_HOOK,new Sprite("res/skills/grapplinghook.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.GRAWP,new Sprite("res/skills/grawp.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.GUARD_AREA,new Sprite("res/skills/guardarea.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.HIPPOGRYFF,new Sprite("res/skills/hippogryff.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.HOLLOW_MAN,new Sprite("res/skills/hollow.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.HORCRUX,new Sprite("res/skills/horkrux.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.ILLUSION,new Sprite("res/skills/illusion.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.IMPERIO,new Sprite("res/skills/imperio.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.I_SHALL_NOT_TELL_LIES,new Sprite("res/skills/ishallnottelllies.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.LIGHTNING_STRIKE,new Sprite("res/skills/lightningstrike.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.LORD_VILLE,new Sprite("res/skills/lordville.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.FIST_BARRAGE,new Sprite("res/skills/messup.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.NORMAL_FORM,new Sprite("res/skills/normalform.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.OCCULT_KNOWLEDGE,new Sprite("res/skills/occultknowledge.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.PETRIFY,new Sprite("res/skills/petrify.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.PHOENIX_TELEPORTATION,new Sprite("res/skills/phoenixportation.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.PLANT,new Sprite("res/skills/plant.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.RABBIT_SLED,new Sprite("res/skills/rabbitsled.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.ROCK_THROW,new Sprite("res/skills/rockthrow.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.ROPES,new Sprite("res/skills/roperoot.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.RUNE_TRAP,new Sprite("res/skills/runetrap.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.SCAN,new Sprite("res/skills/scan.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.SEND_IDEFIX,new Sprite("res/skills/sendidefix.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.SHADOW_ARMOR,new Sprite("res/skills/shadowarmor.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.SHADOW_SPEARS,new Sprite("res/skills/shadowspears.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.SHADOW_WALK,new Sprite("res/skills/shadowwalk.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.SHADOW_WALL,new Sprite("res/skills/shadowwall.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.SHADOW_WAVE,new Sprite("res/skills/shadowwave.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.SKULLDUGGERY,new Sprite("res/skills/skulduggery.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.SMOKE_SCREEN,new Sprite("res/skills/smokescreen.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.STUPOR,new Sprite("res/skills/stupor.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.TALL_GRASS,new Sprite("res/skills/tallgrass.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.TARNING,new Sprite("res/skills/tarning.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.TAUNT,new Sprite("res/skills/taunt.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.TELEPORT,new Sprite("res/skills/teleport.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.TEND_THE_GARDEN,new Sprite("res/skills/tendingthegarden.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.THROW_GRANADE,new Sprite("res/skills/throwgranade.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.TOSSIN,new Sprite("res/skills/tossin.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.TRACKING,new Sprite("res/skills/tracking.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.TRUE_VISION,new Sprite("res/skills/truevision.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.VOODOO_SHIT,new Sprite("res/skills/voodooshit.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.WEAPON_SWING,new Sprite("res/skills/weaponswing.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.WIND_WALL,new Sprite("res/skills/windwall.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.WOOD_WALK,new Sprite("res/skills/woodwalk.png",32,32).getPixels());	
		Resources.PORTRAITSx32.add(SkillLibrary.ZOMBIE_MINIONS,new Sprite("res/skills/zombieminions.png",32,32).getPixels());	
		
	}
}
